# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_API:         ROLE_API
        ROLE_KONSULTA:    ROLE_KONTSULTA
        ROLE_ADMIN:       ROLE_KONTSULTA, ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_API, ROLE_USER, ROLE_KONTSULTA, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            http_basic:   true
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            form_login:
                login_path: /%locale%/login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            anonymous:    true
            remember_me:
                secret: '%secret%'

    access_control:
        - { path: ^/errolda-txartela, role: ROLE_API }
        - { path: ^/[a-z]+/biztanleak, role: ROLE_KONTSULTA }
        - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }